<?php
declare(strict_types=1);
/*
 * The community "what-if" bank.
 *
 * Phase 1 stub: renders the canonical questions read-only so the links from the
 * landing page resolve. Voting and proposing (login-gated) arrive in a later
 * phase, once facilitator accounts exist. New questions will then appear
 * immediately and be moderated post-hoc.
 */
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>The what-if bank — Desirable Futures with robots</title>
  <meta name="description" content="A growing bank of inversion prompts for the Desirable Futures with Robots workshop series — vote for your favourites and propose your own." />
  <link rel="icon" type="image/svg+xml" href="assets/favicon.svg" />
  <link rel="icon" type="image/png" sizes="32x32" href="assets/favicon-32.png" />
  <link rel="apple-touch-icon" sizes="180x180" href="assets/favicon-180.png" />
  <link rel="stylesheet" href="styles.css" />
</head>
<body>

<a class="skip-link" href="#top">Skip to main content</a>

<header class="site-header">
  <a class="wordmark" href="index.php">
    <span>Desirable Futures</span><em>&nbsp;with robots</em>
  </a>
  <nav class="site-nav">
    <a href="index.php#proposition">Manifesto</a>
    <a href="index.php#series">Series</a>
    <a href="index.php#coordinators">Coordinators</a>
    <a class="cta" href="index.php#join">Join&nbsp;→</a>
  </nav>
</header>

<main id="top" tabindex="-1">

  <section class="section section--whatif" id="whatifs">
    <div class="section__marker"><span class="numeral">?</span><span class="label">The What-if Bank</span></div>

    <h2 class="section__title">Reversing the narratives, together.</h2>

    <div class="prose prose--narrow">
      <p>
        Each workshop opens with a <em>what if</em> that reverses one element of the
        dominant framing, then asks participants to imagine a desirable future
        growing from it. Below is the shared bank — free to use and remix.
      </p>
    </div>

    <ol class="whatifs">
      <li class="whatif">
        <span class="whatif__num">01</span>
        <p class="whatif__text">What if robots <em>didn't always say yes</em>, but <em>questioned</em> you?</p>
      </li>
      <li class="whatif">
        <span class="whatif__num">02</span>
        <p class="whatif__text">What if a robot was <em>clumsy</em>, and sometimes needed our <em>help</em>?</p>
      </li>
      <li class="whatif">
        <span class="whatif__num">03</span>
        <p class="whatif__text">What if a robot didn't try to <em>save</em> your time, but to <em>waste it well</em>?</p>
      </li>
      <li class="whatif">
        <span class="whatif__num">04</span>
        <p class="whatif__text">What if a robot brought you <em>something you never asked for</em>?</p>
      </li>
    </ol>

    <div class="prose prose--narrow">
      <p class="emphasis">
        Soon: sign in as a facilitator to <strong>vote for your favourites</strong> and
        <strong>propose your own</strong>. New questions will appear here straight away.
      </p>
      <p>
        In the meantime, <a href="mailto:severin.lemaignan@iiia.csic.es?subject=Proposing%20a%20what%20if">send us a <em>what if</em></a>
        and we'll add it to the bank.
      </p>
    </div>
  </section>

</main>

<footer class="site-footer">
  <div class="site-footer__rule"></div>
  <div class="site-footer__grid">
    <p class="footer-mark">Desirable Futures <em>with robots</em></p>
    <p class="footer-meta">
      A distributed workshop series · 2026—2027<br />
      Final event April 2027 · An open collective initiative
    </p>
    <p class="footer-license">
      All materials shared under <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>.<br />
      <strong>Design and images generated by Generative AI.</strong><br />
    </p>
  </div>
</footer>

<script src="script.js"></script>
</body>
</html>
