</main>

<footer class="site-footer">
  <div class="site-footer__rule"></div>
  <div class="site-footer__grid">
    <p class="footer-mark">Desirable Futures <em>with robots</em></p>
    <p class="footer-meta">
      A distributed workshop series · 2026—2027<br />
      Final event April 2027 · An open collective initiative
    </p>
    <p class="footer-license">
      All materials shared under <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>.<br />
      <strong>Design and images generated by Generative AI.</strong><br />
    </p>
  </div>
</footer>

<?= $page_scripts ?? '' ?>
<script src="script.js"></script>
</body>
</html>
